# Generated by Django 4.2.6 on 2023-11-25 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("cat_Id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("url", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="category/")),
                ("add_date", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                ("Post_Id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("url", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="post/")),
                ("name", models.CharField(max_length=100)),
                (
                    "cat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="First_blog.category",
                    ),
                ),
            ],
        ),
    ]
